### PR TITLE
Allow user to choose valueEncoding

### PR DESCRIPTION
**Pull request by vespakoen**
I tried to use the changes-feed in the browser, unfortunately the buffer doesn't work correctly there:
`TypeError: value.toArrayBuffer is not a function`

I also would like my values to be json, and I don't see a reason why it should explicitly be a buffer?

This is a breaking change, so it this were to be accepted, I guess you should bump the major version.

Thanks!

### CODE REVIEW

**Comment by vespakoen** [comment]
Ouch... I created a new branch based on my master branch that contains my other pull request, if you want me to seperate it into a new pull request, let me know.

**Comment by mafintosh** [comment]
The error you are encountering is probably because your browserify i out of date. try upgrading to the latest one. I've seen it before.

**Comment by mafintosh** [comment]
Could we instead support a `valueEncoding` option in the constructor?

**Comment by mafintosh** [comment]
i see you already did that in #3 - commented there :)

**Comment by vespakoen** [comment]
Alright! thanks for the heads up, didn't see #3 (not from me)
#3 seems to solve it better so I am closing this one.

Thanks!

**Pull request closed without merging**
